# Generated by Django 5.2.9 on 2026-01-02 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MomDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mom_diary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '엄마 마음 일기장',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('happy', '😊 행복해요'), ('peaceful', '😌 평온해요'), ('tired', '😫 피곤해요'), ('stressed', '😰 스트레스받아요'), ('sad', '😢 슬퍼요'), ('angry', '😠 화나요'), ('confused', '😕 혼란스러워요')], default='peaceful', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('ai_care_response', models.TextField(blank=True, help_text='AI가 생성한 공감 및 조언', null=True)),
                ('ai_response_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_secret', models.BooleanField(default=False, help_text='비공개 일기 여부')),
                ('tags', models.CharField(blank=True, help_text='쉼표로 구분 (육아, 부부관계, 취업, ...)', max_length=500)),
                ('diary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='map.momdiary')),
            ],
            options={
                'verbose_name_plural': '일기 항목',
                'ordering': ['-created_at'],
            },
        ),
    ]
