# Generated by Django 5.2.9 on 2026-01-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momdiary',
            name='user',
        ),
        migrations.DeleteModel(
            name='DiaryEntry',
        ),
        migrations.DeleteModel(
            name='MomDiary',
        ),
    ]
