# Generated by Django 6.0 on 2025-12-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyquest',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
