# Generated by Django 5.2.9 on 2026-01-02 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='채팅방 제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='채팅방 설명')),
                ('category', models.CharField(choices=[('general', '일반수다'), ('work', '퇴근후수다'), ('parenting', '육아이야기'), ('tips', '꿀팁공유')], default='general', max_length=20, verbose_name='카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('max_members', models.IntegerField(default=100, verbose_name='최대 멤버 수')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_chatrooms', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='참여일')),
                ('last_read_at', models.DateTimeField(auto_now=True, verbose_name='마지막 읽은 시간')),
                ('is_muted', models.BooleanField(default=False, verbose_name='알림 차단')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom', verbose_name='채팅방')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅방 멤버',
                'verbose_name_plural': '채팅방 멤버',
                'ordering': ['-joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(related_name='joined_chatrooms', through='chat.ChatRoomMember', to=settings.AUTH_USER_MODEL, verbose_name='멤버'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('is_edited', models.BooleanField(default=False, verbose_name='수정 여부')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='chat_chatme_room_id_df087f_idx')],
            },
        ),
    ]
