# Generated by Django 5.2.9 on 2026-01-02 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidnightChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='🌙 새벽 2시의 수다', max_length=100, verbose_name='채팅방 제목')),
                ('description', models.TextField(default='새벽 수유로 외로운 엄마들의 따뜻한 수다 공간', verbose_name='채팅방 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('start_hour', models.IntegerField(default=0, verbose_name='시작 시간 (00:00)')),
                ('end_hour', models.IntegerField(default=5, verbose_name='종료 시간 (05:00)')),
            ],
            options={
                'verbose_name': '새벽 2시 채팅방',
                'verbose_name_plural': '새벽 2시 채팅방',
            },
        ),
        migrations.CreateModel(
            name='MidnightChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='세션 ID (익명 식별용)')),
                ('anonymous_nickname', models.CharField(default='익명의 엄마', max_length=20, verbose_name='익명 닉네임')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.midnightchatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '새벽 2시 메시지',
                'verbose_name_plural': '새벽 2시 메시지',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['room', '-created_at'], name='chat_midnig_room_id_249584_idx'), models.Index(fields=['session_id'], name='chat_midnig_session_c9f232_idx')],
            },
        ),
    ]
