# Generated by Django 5.2.9 on 2025-12-28 13:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('real_name', models.CharField(max_length=30, verbose_name='이름')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('jumin', models.CharField(max_length=20, verbose_name='주민번호')),
                ('phone', models.CharField(max_length=20, verbose_name='휴대폰 번호')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='주소')),
                ('grade', models.CharField(choices=[('seed', '🌱 새싹회원'), ('general', '🌿 일반회원'), ('vip', '🌸 우수회원'), ('admin', '👑 운영진')], default='seed', max_length=10, verbose_name='회원 등급')),
                ('gender', models.CharField(choices=[('M', '남자'), ('F', '여자')], default='F', max_length=1, verbose_name='성별')),
                ('child_school', models.CharField(choices=[('none', '자녀 없음'), ('elementary', '초등학생'), ('middle', '중학생'), ('high', '고등학생')], default='none', max_length=20, verbose_name='자녀 학급')),
                ('terms_agreed', models.BooleanField(default=False, verbose_name='약관 동의')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
            ],
            options={
                'verbose_name': '관리자',
                'verbose_name_plural': '2. 관리자(스태프) 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
            ],
            options={
                'verbose_name': '일반 회원',
                'verbose_name_plural': '1. 일반 회원 관리',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
