# Generated by Django 6.0 on 2025-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='children_stages',
            field=models.JSONField(blank=True, default=list, verbose_name='자녀 학령(복수)'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_children',
            field=models.BooleanField(default=False, verbose_name='자녀 유무'),
        ),
    ]
