# Generated by Django 6.0 on 2025-12-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_children_stages_user_has_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='child_school',
        ),
    ]
