# Generated by Django 6.0 on 2026-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_point_alter_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_detail',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='상세주소'),
        ),
    ]
