# Generated by Django 5.2.9 on 2026-01-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_address_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('blocked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username', 'blocked_until'], name='accounts_si_usernam_a1631d_idx')],
            },
        ),
    ]
