# Generated by Django 5.2.9 on 2025-12-29 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='기록 날짜')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='키(cm)')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='몸무게(kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '성장 기록',
                'verbose_name_plural': '성장 기록',
                'ordering': ['record_date'],
                'unique_together': {('user', 'record_date')},
            },
        ),
    ]
