# Generated by Django 6.0.1 on 2026-01-09 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipestep_recipe_recipepost_recipeimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.recipecomment'),
        ),
    ]
