# Generated by Django 5.2.9 on 2025-12-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_fleaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleaitem',
            name='price',
            field=models.IntegerField(verbose_name='가격(원)'),
        ),
    ]
