# Generated by Django 5.2.9 on 2025-12-29 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_fleaitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fleaitem',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_flea_items', to=settings.AUTH_USER_MODEL, verbose_name='찜한 사용자'),
        ),
    ]
