# Generated by Django 5.2.9 on 2025-12-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_fleacomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleacomment',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='비밀글 비밀번호'),
        ),
    ]
