# Generated by Django 5.2.9 on 2025-12-29 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_fleacomment_password'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleacomment',
            options={'ordering': ['-created_at'], 'verbose_name': '벼룩시장 댓글', 'verbose_name_plural': '벼룩시장 댓글'},
        ),
        migrations.AlterModelOptions(
            name='fleaitem',
            options={'ordering': ['-created_at'], 'verbose_name': '벼룩시장', 'verbose_name_plural': '벼룩시장'},
        ),
        migrations.AlterModelOptions(
            name='freepost',
            options={'verbose_name': '자유게시판', 'verbose_name_plural': '자유게시판'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.AddField(
            model_name='fleaitem',
            name='status',
            field=models.CharField(choices=[('selling', '판매중'), ('reserved', '예약중'), ('sold', '판매완료')], default='selling', max_length=20, verbose_name='거래 상태'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, verbose_name='알림 메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='발신자')),
                ('flea_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.fleacomment', verbose_name='댓글')),
                ('flea_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.fleaitem', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
            },
        ),
    ]
