# Generated by Django 5.2.9 on 2026-01-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_remove_notification_actor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.AddField(
            model_name='notification',
            name='flea_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.fleaitem', verbose_name='중고장터 아이템'),
        ),
        migrations.AddField(
            model_name='notification',
            name='free_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.freepost', verbose_name='자유게시판 글'),
        ),
        migrations.AddField(
            model_name='notification',
            name='pet_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.petpost', verbose_name='반려동물 게시글'),
        ),
    ]
