# Generated by Django 5.2.9 on 2026-01-02 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_notification_post_notification_flea_item_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('category', models.CharField(choices=[('all', '전체보기'), ('baby', '육아용품 핫딜'), ('life', '생활용품 핫딜'), ('event', '이벤트/체험단')], default='all', max_length=10, verbose_name='카테고리')),
                ('link', models.URLField(blank=True, null=True, verbose_name='상품 링크')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='가격')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('views', models.IntegerField(default=0, verbose_name='조회수')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '핫딜공유',
                'verbose_name_plural': '핫딜공유',
                'ordering': ['-created_at'],
            },
        ),
    ]
