# Generated by Django 5.2.9 on 2026-01-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_hotdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleaitem',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
    ]
