# Generated by Django 5.2.9 on 2026-01-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_parentinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinginfo',
            name='cognitive_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='인지발달(0-100)'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='language_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='언어발달(0-100)'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='month_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='월령(개월)'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='physical_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='신체발달(0-100)'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='social_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='사회성발달(0-100)'),
        ),
    ]
