# Generated by Django 5.2.9 on 2026-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_parentinginfo_cognitive_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freepost',
            options={'ordering': ['-created_at'], 'verbose_name': '자유게시판', 'verbose_name_plural': '자유게시판'},
        ),
        migrations.AddField(
            model_name='freepost',
            name='category',
            field=models.CharField(choices=[('all', '전체보기'), ('mom', '육아수다'), ('husband', '남편뒷담화'), ('family', '시댁/친정'), ('preg', '임신출산')], default='mom', max_length=20, verbose_name='카테고리'),
        ),
    ]
