# Generated by Django 5.2.9 on 2026-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_alter_freepost_options_freepost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명'),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='category',
            field=models.CharField(choices=[('all', '전체보기'), ('mom', '육아수다'), ('husband', '남편뒷담화'), ('family', '시댁/친정'), ('preg', '임신출산'), ('bamboo', '대나무숲')], default='mom', max_length=20, verbose_name='카테고리'),
        ),
    ]
