# Generated by Django 5.2.9 on 2026-01-02 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_freepost_is_anonymous_alter_freepost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='reaction_cheer',
            field=models.IntegerField(default=0, verbose_name='축하해요'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='reaction_courage',
            field=models.IntegerField(default=0, verbose_name='힘내세요'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='reaction_empathy',
            field=models.IntegerField(default=0, verbose_name='공감해요'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='reaction_support',
            field=models.IntegerField(default=0, verbose_name='응원해요'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='reaction_thanks',
            field=models.IntegerField(default=0, verbose_name='고마워요'),
        ),
        migrations.CreateModel(
            name='FreePostReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('empathy', '공감해요 🤝'), ('courage', '힘내세요 💪'), ('cheer', '축하해요 🎉'), ('support', '응원해요 👏'), ('thanks', '고마워요 🙏')], max_length=20, verbose_name='리액션 타입')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='board.freepost', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '자유게시판 감정리액션',
                'verbose_name_plural': '자유게시판 감정리액션',
                'ordering': ['-created_at'],
                'unique_together': {('post', 'user', 'reaction_type')},
            },
        ),
    ]
