# Generated by Django 5.2.9 on 2026-01-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_momdiary_diaryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='hotdeal_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.hotdeal', verbose_name='핫딜공유 게시글'),
        ),
        migrations.AddField(
            model_name='notification',
            name='parenting_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.parentinginfo', verbose_name='육아정보 게시글'),
        ),
    ]
