# Generated by Django 5.2.9 on 2026-01-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_notification_hotdeal_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='대나무숲 공유 (익명 공개)'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='is_secret',
            field=models.BooleanField(default=True, help_text='비공개 일기 여부 (기본값: True)'),
        ),
    ]
