# Generated by Django 5.2.9 on 2026-01-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_diaryentry_is_anonymous_alter_diaryentry_is_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinginfo',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='키(cm)'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='몸무게(kg)'),
        ),
    ]
