# Generated by Django 5.2.9 on 2026-01-05 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_parentinginfo_height_parentinginfo_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='bookmark_count',
            field=models.IntegerField(default=0, verbose_name='저장수'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='댓글수'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='구/군'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='dong',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='동/읍/면'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='운영진 고정'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='고정 시간'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='popularity_score',
            field=models.FloatField(default=0, verbose_name='인기도 점수'),
        ),
        migrations.AddField(
            model_name='freepost',
            name='region',
            field=models.CharField(blank=True, choices=[('seoul', '서울시'), ('gyeonggi', '경기도'), ('incheon', '인천시'), ('daejeon', '대전시'), ('daegu', '대구시'), ('busan', '부산시'), ('gwangju', '광주시'), ('ulsan', '울산시'), ('sejong', '세종시'), ('other', '기타')], max_length=20, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='bookmark_count',
            field=models.IntegerField(default=0, verbose_name='저장수'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='댓글수'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='구/군'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='dong',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='동/읍/면'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='운영진 고정'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='고정 시간'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='popularity_score',
            field=models.FloatField(default=0, verbose_name='인기도 점수'),
        ),
        migrations.AddField(
            model_name='hotdeal',
            name='region',
            field=models.CharField(blank=True, choices=[('seoul', '서울시'), ('gyeonggi', '경기도'), ('incheon', '인천시'), ('daejeon', '대전시'), ('daegu', '대구시'), ('busan', '부산시'), ('gwangju', '광주시'), ('ulsan', '울산시'), ('sejong', '세종시'), ('other', '기타')], max_length=20, null=True, verbose_name='지역'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='bookmark_count',
            field=models.IntegerField(default=0, verbose_name='저장수'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='댓글수'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='구/군'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='dong',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='동/읍/면'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='운영진 고정'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='고정 시간'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='popularity_score',
            field=models.FloatField(default=0, verbose_name='인기도 점수'),
        ),
        migrations.AddField(
            model_name='parentinginfo',
            name='region',
            field=models.CharField(blank=True, choices=[('seoul', '서울시'), ('gyeonggi', '경기도'), ('incheon', '인천시'), ('daejeon', '대전시'), ('daegu', '대구시'), ('busan', '부산시'), ('gwangju', '광주시'), ('ulsan', '울산시'), ('sejong', '세종시'), ('other', '기타')], max_length=20, null=True, verbose_name='지역'),
        ),
        migrations.AddIndex(
            model_name='freepost',
            index=models.Index(fields=['-is_pinned', '-popularity_score', '-created_at'], name='board_freep_is_pinn_8e7a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='freepost',
            index=models.Index(fields=['region', '-popularity_score'], name='board_freep_region_bd65b6_idx'),
        ),
        migrations.AddIndex(
            model_name='hotdeal',
            index=models.Index(fields=['-is_pinned', '-popularity_score', '-created_at'], name='board_hotde_is_pinn_126c24_idx'),
        ),
        migrations.AddIndex(
            model_name='hotdeal',
            index=models.Index(fields=['region', '-popularity_score'], name='board_hotde_region_ec5461_idx'),
        ),
        migrations.AddIndex(
            model_name='parentinginfo',
            index=models.Index(fields=['-is_pinned', '-popularity_score', '-created_at'], name='board_paren_is_pinn_31ecd0_idx'),
        ),
        migrations.AddIndex(
            model_name='parentinginfo',
            index=models.Index(fields=['region', '-popularity_score'], name='board_paren_region_591657_idx'),
        ),
    ]
