# Generated by Django 5.2.9 on 2026-01-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_freepost_bookmark_count_freepost_comment_count_and_more'),
        ('recipes', '0002_remove_recipestep_recipe_recipepost_recipeimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipe_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.recipepost', verbose_name='요리레시피 게시글'),
        ),
        migrations.AlterField(
            model_name='fleaitem',
            name='status',
            field=models.CharField(choices=[('selling', '판매중'), ('reserved', '예약중'), ('sold', '판매완료'), ('share', '나눔')], default='selling', max_length=20, verbose_name='거래 상태'),
        ),
    ]
