# Generated by Django 5.2.9 on 2026-01-06 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_notification_recipe_post_alter_fleaitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petpost',
            name='image',
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet/', verbose_name='이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.petpost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '반려동물 이미지',
                'verbose_name_plural': '반려동물 이미지',
                'ordering': ['order'],
            },
        ),
    ]
