# Generated by Django 6.0 on 2026-01-06 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_freecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freepost',
            name='is_anonymous',
        ),
        migrations.AlterField(
            model_name='freepost',
            name='category',
            field=models.CharField(choices=[('all', '전체보기'), ('mom', '육아수다'), ('husband', '남편뒷담화'), ('family', '시댁/친정'), ('preg', '임신출산')], default='mom', max_length=20, verbose_name='카테고리'),
        ),
        migrations.CreateModel(
            name='FreePostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='free_attachments/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='board.freepost')),
            ],
        ),
    ]
