# Generated by Django 5.2.9 on 2026-01-06 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_freecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleaReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', '광고/스팸'), ('fraud', '사기 의심'), ('abuse', '욕설/비방'), ('wrong', '잘못된 정보/분류'), ('other', '기타')], max_length=30, verbose_name='신고 사유')),
                ('details', models.TextField(blank=True, verbose_name='상세 내용')),
                ('status', models.CharField(choices=[('pending', '접수'), ('resolved', '처리완료')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 일시')),
                ('flea_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.fleaitem', verbose_name='신고 대상')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flea_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '벼룩시장 신고',
                'verbose_name_plural': '벼룩시장 신고',
                'ordering': ['-created_at'],
            },
        ),
    ]
