# Generated by Django 6.0 on 2026-01-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_fleareport'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleaitem',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='fleaitem',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='거래 희망 위치(주소)'),
        ),
        migrations.AddField(
            model_name='fleaitem',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='status',
            field=models.CharField(choices=[('pending', '접수'), ('in_progress', '확인중'), ('resolved', '처리완료')], default='pending', max_length=20, verbose_name='처리 상태'),
        ),
    ]
