# Generated by Django 5.2.9 on 2026-01-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_fleareport'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinginfo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='parenting/', verbose_name='썸네일 이미지'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='status',
            field=models.CharField(choices=[('pending', '접수'), ('in_progress', '확인중'), ('resolved', '처리완료')], default='pending', max_length=20, verbose_name='처리 상태'),
        ),
    ]
