# Generated by Django 5.2.9 on 2026-01-07 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_parentinginfo_thumbnail_alter_fleareport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parenting/', verbose_name='이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.parentinginfo', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '육아정보 이미지',
                'verbose_name_plural': '육아정보 이미지',
                'ordering': ['order'],
            },
        ),
    ]
