# Generated by Django 5.2.9 on 2026-01-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_questioncard_questionanswer'),
        ('board', '0030_parentingcomment'),
    ]

    operations = [
    ]
