# Generated by Django 5.2.9 on 2026-01-08 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_parentingcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentingimage',
            options={'ordering': ['order', 'id'], 'verbose_name': '육아정보 이미지', 'verbose_name_plural': '육아정보 이미지'},
        ),
        migrations.RemoveField(
            model_name='fleareport',
            name='details',
        ),
        migrations.RemoveField(
            model_name='fleareport',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='fleareport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fleareport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='parentinginfo',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='fleareport',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='처리 완료'),
        ),
        migrations.AddField(
            model_name='fleareport',
            name='report_type',
            field=models.CharField(choices=[('spam', '스팸/광고'), ('fraud', '사기 의심'), ('inappropriate', '부적절한 콘텐츠'), ('etc', '기타')], default='etc', max_length=20, verbose_name='신고 유형'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='신고일'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='flea_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.fleaitem', verbose_name='신고된 상품'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='신고 사유'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='신고자'),
        ),
        # Removed DeleteModel operations for QuestionAnswer/QuestionCard
    ]
