# Generated by Django 5.2.9 on 2026-01-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_alter_parentingimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentingcomment',
            name='images',
            field=models.JSONField(blank=True, default=list, verbose_name='첨부 이미지'),
        ),
    ]
