# Generated by Django 6.0 on 2026-01-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0034_petcounselpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petcounselpost',
            name='is_solved',
        ),
        migrations.AddField(
            model_name='petcounselpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AddField(
            model_name='petcounselpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
