# Generated by Django 6.0 on 2026-01-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0035_remove_petcounselpost_is_solved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetHealthImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_health/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.pethealthpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
