# Generated by Django 5.2.9 on 2026-01-11 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0033_parentingcomment_images'),
        ('board', '0039_petcounselcomment'),
    ]

    operations = [
    ]
