# Generated by Django 5.2.9 on 2026-01-11 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0039_petcounselcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleareport',
            options={'verbose_name': '벼룩시장 신고', 'verbose_name_plural': '벼룩시장 신고'},
        ),
        migrations.RemoveField(
            model_name='fleareport',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='fleareport',
            name='report_type',
        ),
        migrations.AddField(
            model_name='fleaitem',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='위도'),
        ),
        migrations.AddField(
            model_name='fleaitem',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='거래 희망 위치(주소)'),
        ),
        migrations.AddField(
            model_name='fleaitem',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='경도'),
        ),
        migrations.AddField(
            model_name='fleareport',
            name='details',
            field=models.TextField(blank=True, verbose_name='상세 내용'),
        ),
        migrations.AddField(
            model_name='fleareport',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리 일시'),
        ),
        migrations.AddField(
            model_name='fleareport',
            name='status',
            field=models.CharField(choices=[('pending', '접수'), ('in_progress', '확인중'), ('resolved', '처리완료')], default='pending', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AddField(
            model_name='fleareport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 일시'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='신고 일시'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='flea_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='board.fleaitem', verbose_name='신고 대상'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='reason',
            field=models.CharField(choices=[('spam', '광고/스팸'), ('fraud', '사기 의심'), ('abuse', '욕설/비방'), ('wrong', '잘못된 정보/분류'), ('other', '기타')], max_length=30, verbose_name='신고 사유'),
        ),
        migrations.AlterField(
            model_name='fleareport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flea_reports', to=settings.AUTH_USER_MODEL, verbose_name='신고자'),
        ),
    ]
