# Generated by Django 5.2.9 on 2026-01-13 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_remove_freepost_is_anonymous_alter_freepost_category_and_more'),
        ('board', '0033_parentingcomment_images'),
        ('board', '0041_alter_fleareport_options_and_more'),
    ]

    operations = [
    ]
