# Generated by Django 6.0 on 2026-01-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_fleaitem_latitude_fleaitem_location_address_and_more'),
        ('board', '0041_alter_fleareport_options_and_more'),
    ]

    operations = [
    ]
