# Generated by Django 5.2.9 on 2026-01-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0042_merge_20260113_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명 여부'),
        ),
    ]
