# Generated by Django 6.0 on 2026-01-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_merge_20260108_1218'),
        ('board', '0040_merge_20260111_1929'),
        ('board', '0042_merge_20260112_1608'),
        ('board', '0043_freepost_is_anonymous'),
    ]

    operations = [
    ]
