# Generated by Django 6.0 on 2026-01-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0044_merge_20260114_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명 여부'),
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
        migrations.DeleteModel(
            name='QuestionCard',
        ),
    ]
